// Contract Addresses on Worldchain Mainnet (Chain ID: 480)
//
// These defaults are THE LIVE DEPLOYMENT: the contracts whitelisted for
// HumanBondMultisig (app_925d0aaa…), which serves humanbond-lisbon-nu.vercel.app.
// Every one of them was read back off the chain on 2026-08-02, not copied from a doc:
//
//   HumanBond proxy   activeBondCount() = 2, dissolutionDelay() = 259200 (3d)
//   BondVaultModule   humanBond() -> the proxy, and proxy.bondVaultModule() -> it
//   BondNFT/Milestone proxy.bondNft() / proxy.milestoneNft()
//   TIME              proxy.timeToken()
//   Registrar         humanBond() -> the proxy, baseNode = namehash('humandbond.eth')
//
// WHY THIS CHANGED: the previous defaults pointed at a different, abandoned set
// (activeBondCount = 0) whose BondVaultModule entry was in fact a Gnosis Safe
// proxy. None of those addresses are whitelisted, and MiniKit rejects any call to
// a non-whitelisted contract with `invalid_contract` — so in production every
// transaction would have failed. It was never noticed because .env.local runs
// with USE_MOCKS=1, so no real transaction was ever sent against this config.
//
// Anything here is still overridable by the matching NEXT_PUBLIC_* var. Keep the
// defaults and the Developer Portal whitelist in sync — they are one unit.
export const CONTRACT_ADDRESSES = {
  HUMAN_BOND: (process.env.NEXT_PUBLIC_HUMAN_BOND ?? '0x7A9cE44218EFe38E9a98c9a01453aAa3A05bFC82') as `0x${string}`, // Proxy (always use this)
  BOND_NFT: (process.env.NEXT_PUBLIC_BOND_NFT ?? '0xb3E3B17f7c820F742935f26956474252390c369b') as `0x${string}`,
  MILESTONE_NFT: (process.env.NEXT_PUBLIC_MILESTONE_NFT ?? '0x676db63968F70A952d08dC321CAB020a96Ab178c') as `0x${string}`,
  TIME_TOKEN: (process.env.NEXT_PUBLIC_TIME_TOKEN ?? '0x5A2beFadd1541e2133b96CcFf4136093047A1aE9') as `0x${string}`,
  // ENS subname registrar — the third call in the vault-creation batch.
  BOND_REGISTRAR: (process.env.NEXT_PUBLIC_BOND_REGISTRAR ?? '0x32daDB84eA905396e0FD3329D44965c4A09a1944') as `0x${string}`,
} as const

// World App Configuration — nullifiers derive from this app_id (immutable per deploy).
// This is the app the contracts above are whitelisted under; the old default
// (app_bfc32618…) is not even on this Developer Portal team.
export const WORLD_APP_CONFIG = {
  APP_ID: (process.env.NEXT_PUBLIC_WORLD_APP_ID ?? 'app_925d0aaa3d9464e5d61690d94a68b401') as `app_${string}`,
  ACTIONS: {
    PROPOSE_BOND: 'propose-bond',
    ACCEPT_BOND: 'accept-bond',
  },
} as const

// Mini App deep link — embedded in chat messages so recipients can tap back in
export const APP_URL = 'https://worldminiapp.world/mini-app/humanbond' as const

// BondNFT ABI (replaces VowNFT)
export const BOND_NFT_ABI = [
  { "type": "constructor", "inputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "approve", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "balanceOf", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "bondToToken", "inputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }, { "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getApproved", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "getTokenMetadata", "inputs": [{ "name": "id", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "bondId", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "getTokensByBond", "inputs": [{ "name": "bondId", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "", "type": "uint256[]", "internalType": "uint256[]" }], "stateMutability": "view" },
  { "type": "function", "name": "humanBondContract", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "imageURI", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "isApprovedForAll", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "operator", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "mintBondNft", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "_partnerA", "type": "address", "internalType": "address" }, { "name": "_partnerB", "type": "address", "internalType": "address" }, { "name": "_bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "_bondId", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "name", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "ownerOf", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "renounceOwnership", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }, { "name": "data", "type": "bytes", "internalType": "bytes" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setApprovalForAll", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }, { "name": "approved", "type": "bool", "internalType": "bool" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setHumanBondContract", "inputs": [{ "name": "contractAddress", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setImageURI", "inputs": [{ "name": "newURI", "type": "string", "internalType": "string" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "supportsInterface", "inputs": [{ "name": "interfaceId", "type": "bytes4", "internalType": "bytes4" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "symbol", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "tokenMetadata", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "bondId", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "tokenURI", "inputs": [{ "name": "id", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "totalSupply", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "transferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "transferOwnership", "inputs": [{ "name": "newOwner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "event", "name": "Approval", "inputs": [{ "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "approved", "type": "address", "indexed": true, "internalType": "address" }, { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "ApprovalForAll", "inputs": [{ "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "operator", "type": "address", "indexed": true, "internalType": "address" }, { "name": "approved", "type": "bool", "indexed": false, "internalType": "bool" }], "anonymous": false },
  { "type": "event", "name": "BondMinted", "inputs": [{ "name": "bondId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }, { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" }, { "name": "to", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "HumanBondContractSet", "inputs": [{ "name": "contractAddress", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "ImageURISet", "inputs": [{ "name": "newURI", "type": "string", "indexed": false, "internalType": "string" }], "anonymous": false },
  { "type": "event", "name": "OwnershipTransferred", "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "Transfer", "inputs": [{ "name": "from", "type": "address", "indexed": true, "internalType": "address" }, { "name": "to", "type": "address", "indexed": true, "internalType": "address" }, { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" }], "anonymous": false },
  { "type": "error", "name": "BondNFT__InvalidAddress", "inputs": [] },
  { "type": "error", "name": "BondNFT__TransfersDisabled", "inputs": [] },
  { "type": "error", "name": "BondNFT__UnauthorizedMinter", "inputs": [] },
  { "type": "error", "name": "ERC721IncorrectOwner", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }, { "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InsufficientApproval", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "ERC721InvalidApprover", "inputs": [{ "name": "approver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidOperator", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidReceiver", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidSender", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721NonexistentToken", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "OwnableInvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "OwnableUnauthorizedAccount", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "StringsInsufficientHexLength", "inputs": [{ "name": "value", "type": "uint256", "internalType": "uint256" }, { "name": "length", "type": "uint256", "internalType": "uint256" }] }
] as const

// MilestoneNFT ABI
export const MILESTONE_NFT_ABI = [
  { "type": "constructor", "inputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "approve", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "balanceOf", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "freezeMilestones", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "frozen", "inputs": [], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "getApproved", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "humanBondContract", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "isApprovedForAll", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "operator", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "latestYear", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "milestoneUrIs", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "mintMilestone", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "year", "type": "uint256", "internalType": "uint256" }, { "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondId", "type": "bytes32", "internalType": "bytes32" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "name", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "ownerOf", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "renounceOwnership", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "safeTransferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }, { "name": "data", "type": "bytes", "internalType": "bytes" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setApprovalForAll", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }, { "name": "approved", "type": "bool", "internalType": "bool" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setHumanBondContract", "inputs": [{ "name": "contractAddress", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setMilestoneURI", "inputs": [{ "name": "year", "type": "uint256", "internalType": "uint256" }, { "name": "uri", "type": "string", "internalType": "string" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "supportsInterface", "inputs": [{ "name": "interfaceId", "type": "bytes4", "internalType": "bytes4" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "symbol", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "tokenData", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondId", "type": "bytes32", "internalType": "bytes32" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "claimedAt", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "tokenURI", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "tokenYear", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "year", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "totalSupply", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "transferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "transferOwnership", "inputs": [{ "name": "newOwner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "event", "name": "Approval", "inputs": [{ "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "approved", "type": "address", "indexed": true, "internalType": "address" }, { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "ApprovalForAll", "inputs": [{ "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "operator", "type": "address", "indexed": true, "internalType": "address" }, { "name": "approved", "type": "bool", "indexed": false, "internalType": "bool" }], "anonymous": false },
  { "type": "event", "name": "HumanBondContractSet", "inputs": [{ "name": "contractAddress", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "MilestoneMinted", "inputs": [{ "name": "user", "type": "address", "indexed": true, "internalType": "address" }, { "name": "year", "type": "uint256", "indexed": false, "internalType": "uint256" }, { "name": "tokenId", "type": "uint256", "indexed": false, "internalType": "uint256" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "MilestoneURISet", "inputs": [{ "name": "year", "type": "uint256", "indexed": true, "internalType": "uint256" }, { "name": "uri", "type": "string", "indexed": false, "internalType": "string" }], "anonymous": false },
  { "type": "event", "name": "MilestonesFrozen", "inputs": [], "anonymous": false },
  { "type": "event", "name": "OwnershipTransferred", "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "Transfer", "inputs": [{ "name": "from", "type": "address", "indexed": true, "internalType": "address" }, { "name": "to", "type": "address", "indexed": true, "internalType": "address" }, { "name": "tokenId", "type": "uint256", "indexed": true, "internalType": "uint256" }], "anonymous": false },
  { "type": "error", "name": "ERC721IncorrectOwner", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }, { "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InsufficientApproval", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }, { "name": "tokenId", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "ERC721InvalidApprover", "inputs": [{ "name": "approver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidOperator", "inputs": [{ "name": "operator", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidReceiver", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721InvalidSender", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC721NonexistentToken", "inputs": [{ "name": "tokenId", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "MilestoneNFT__Frozen", "inputs": [] },
  { "type": "error", "name": "MilestoneNFT__InvalidAddress", "inputs": [] },
  { "type": "error", "name": "MilestoneNFT__NotAuthorized", "inputs": [] },
  { "type": "error", "name": "MilestoneNFT__TransfersDisabled", "inputs": [] },
  { "type": "error", "name": "MilestoneNFT__URI_NotFound", "inputs": [{ "name": "year", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "OwnableInvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "OwnableUnauthorizedAccount", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "StringsInsufficientHexLength", "inputs": [{ "name": "value", "type": "uint256", "internalType": "uint256" }, { "name": "length", "type": "uint256", "internalType": "uint256" }] }
] as const

// HumanBond ABI (V3 — proxy)
export const HUMAN_BOND_ABI = [
  { "type": "function", "name": "GROUP_ID", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "UPGRADE_INTERFACE_VERSION", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "accept", "inputs": [{ "name": "proposer", "type": "address", "internalType": "address" }, { "name": "root", "type": "uint256", "internalType": "uint256" }, { "name": "acceptorNullifier", "type": "uint256", "internalType": "uint256" }, { "name": "proof", "type": "uint256[8]", "internalType": "uint256[8]" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "activeBondCount", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "activeBondOf", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "bondIds", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "bondNft", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract BondNFT" }], "stateMutability": "view" },
  { "type": "function", "name": "bonds", "inputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "lastClaim", "type": "uint256", "internalType": "uint256" }, { "name": "lastMilestoneYear", "type": "uint256", "internalType": "uint256" }, { "name": "active", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "cancelDissolutionRequest", "inputs": [{ "name": "partner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "cancelProposal", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "claimYield", "inputs": [{ "name": "partner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "dayDuration", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "dissolutionDelay", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "dissolutionRequests", "inputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "requester", "type": "address", "internalType": "address" }, { "name": "requestedAt", "type": "uint256", "internalType": "uint256" }, { "name": "active", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "executeDissolution", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "externalNullifierAccept", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "externalNullifierPropose", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getBond", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct HumanBond.Bond", "components": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "lastClaim", "type": "uint256", "internalType": "uint256" }, { "name": "lastMilestoneYear", "type": "uint256", "internalType": "uint256" }, { "name": "active", "type": "bool", "internalType": "bool" }] }], "stateMutability": "view" },
  { "type": "function", "name": "bondEpoch", "inputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getBondId", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "pure" },
  { "type": "function", "name": "getBondStart", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getBondView", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "v", "type": "tuple", "internalType": "struct HumanBond.BondView", "components": [{ "name": "partnerA", "type": "address", "internalType": "address" }, { "name": "partnerB", "type": "address", "internalType": "address" }, { "name": "bondStart", "type": "uint256", "internalType": "uint256" }, { "name": "lastClaim", "type": "uint256", "internalType": "uint256" }, { "name": "lastMilestoneYear", "type": "uint256", "internalType": "uint256" }, { "name": "active", "type": "bool", "internalType": "bool" }, { "name": "pendingYield", "type": "uint256", "internalType": "uint256" }, { "name": "bondId", "type": "bytes32", "internalType": "bytes32" }] }], "stateMutability": "view" },
  { "type": "function", "name": "getCurrentMilestoneYear", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getDissolutionRequest", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct HumanBond.DissolutionRequest", "components": [{ "name": "requester", "type": "address", "internalType": "address" }, { "name": "requestedAt", "type": "uint256", "internalType": "uint256" }, { "name": "active", "type": "bool", "internalType": "bool" }] }], "stateMutability": "view" },
  { "type": "function", "name": "getIncomingProposals", "inputs": [{ "name": "user", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "tuple[]", "internalType": "struct HumanBond.Proposal[]", "components": [{ "name": "proposer", "type": "address", "internalType": "address" }, { "name": "proposed", "type": "address", "internalType": "address" }, { "name": "timestamp", "type": "uint256", "internalType": "uint256" }] }], "stateMutability": "view" },
  { "type": "function", "name": "getPendingYield", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getProposal", "inputs": [{ "name": "proposer", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct HumanBond.Proposal", "components": [{ "name": "proposer", "type": "address", "internalType": "address" }, { "name": "proposed", "type": "address", "internalType": "address" }, { "name": "timestamp", "type": "uint256", "internalType": "uint256" }] }], "stateMutability": "view" },
  { "type": "function", "name": "getUserDashboard", "inputs": [{ "name": "user", "type": "address", "internalType": "address" }], "outputs": [{ "name": "d", "type": "tuple", "internalType": "struct HumanBond.UserDashboard", "components": [{ "name": "isBonded", "type": "bool", "internalType": "bool" }, { "name": "hasProposal", "type": "bool", "internalType": "bool" }, { "name": "partner", "type": "address", "internalType": "address" }, { "name": "pendingYield", "type": "uint256", "internalType": "uint256" }, { "name": "timeBalance", "type": "uint256", "internalType": "uint256" }] }], "stateMutability": "view" },
  { "type": "function", "name": "hasPendingProposal", "inputs": [{ "name": "proposer", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "initialize", "inputs": [{ "name": "_worldIdRouter", "type": "address", "internalType": "address" }, { "name": "_bondNft", "type": "address", "internalType": "address" }, { "name": "_timeToken", "type": "address", "internalType": "address" }, { "name": "_milestoneNft", "type": "address", "internalType": "address" }, { "name": "_appId", "type": "string", "internalType": "string" }, { "name": "_actionPropose", "type": "string", "internalType": "string" }, { "name": "_actionAccept", "type": "string", "internalType": "string" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "isBonded", "inputs": [{ "name": "a", "type": "address", "internalType": "address" }, { "name": "b", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "lastDissolutionTimestamp", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "manualCheckAndMint", "inputs": [{ "name": "partner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "milestoneNft", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract MilestoneNFT" }], "stateMutability": "view" },
  { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "proposals", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "proposer", "type": "address", "internalType": "address" }, { "name": "proposed", "type": "address", "internalType": "address" }, { "name": "timestamp", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "proposalsFor", "inputs": [{ "name": "", "type": "address", "internalType": "address" }, { "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "propose", "inputs": [{ "name": "proposed", "type": "address", "internalType": "address" }, { "name": "root", "type": "uint256", "internalType": "uint256" }, { "name": "proposerNullifier", "type": "uint256", "internalType": "uint256" }, { "name": "proof", "type": "uint256[8]", "internalType": "uint256[8]" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "proposerIndex", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "proxiableUUID", "inputs": [], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "rebondCooldown", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "rejectProposal", "inputs": [{ "name": "proposer", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "renounceOwnership", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "requestDissolution", "inputs": [{ "name": "partner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "bondVaultModule", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "setBondNft", "inputs": [{ "name": "_bondNft", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setBondVaultModule", "inputs": [{ "name": "_bondVaultModule", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setDayDuration", "inputs": [{ "name": "_day", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setDissolutionDelay", "inputs": [{ "name": "_delay", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setMilestoneNft", "inputs": [{ "name": "_milestoneNft", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setRebondCooldown", "inputs": [{ "name": "_cooldown", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setWorldId", "inputs": [{ "name": "_worldId", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setYearDuration", "inputs": [{ "name": "_year", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "timeToken", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract TimeToken" }], "stateMutability": "view" },
  { "type": "function", "name": "totalDissolutionCount", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "transferOwnership", "inputs": [{ "name": "newOwner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "upgradeToAndCall", "inputs": [{ "name": "newImplementation", "type": "address", "internalType": "address" }, { "name": "data", "type": "bytes", "internalType": "bytes" }], "outputs": [], "stateMutability": "payable" },
  { "type": "function", "name": "worldId", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract IWorldID" }], "stateMutability": "view" },
  { "type": "function", "name": "yearDuration", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "event", "name": "AnniversaryAchieved", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "year", "type": "uint256", "indexed": false, "internalType": "uint256" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "BondDissolved", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "BondNftUpdated", "inputs": [{ "name": "newBondNft", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "DissolutionDelayUpdated", "inputs": [{ "name": "newDissolutionDelay", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "DissolutionRequestCancelled", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "DissolutionRequested", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "requester", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "BondVaultModuleUpdated", "inputs": [{ "name": "newBondVaultModule", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "VaultSettled", "inputs": [{ "name": "bondId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }], "anonymous": false },
  { "type": "event", "name": "VaultSettlementFailed", "inputs": [{ "name": "bondId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }], "anonymous": false },
  { "type": "event", "name": "Initialized", "inputs": [{ "name": "version", "type": "uint64", "indexed": false, "internalType": "uint64" }], "anonymous": false },
  { "type": "event", "name": "MilestoneNftUpdated", "inputs": [{ "name": "newMilestoneNft", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "OwnershipTransferred", "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "ProposalAccepted", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "ProposalCancelled", "inputs": [{ "name": "proposer", "type": "address", "indexed": true, "internalType": "address" }, { "name": "proposed", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "ProposalCreated", "inputs": [{ "name": "proposer", "type": "address", "indexed": true, "internalType": "address" }, { "name": "proposed", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "ProposalRejected", "inputs": [{ "name": "proposer", "type": "address", "indexed": true, "internalType": "address" }, { "name": "proposed", "type": "address", "indexed": true, "internalType": "address" }, { "name": "timestamp", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "RebondCooldownUpdated", "inputs": [{ "name": "newCooldown", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "Upgraded", "inputs": [{ "name": "implementation", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "WorldIdUpdated", "inputs": [{ "name": "newWorldId", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "YearDurationUpdated", "inputs": [{ "name": "newYearDuration", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "YieldClaimed", "inputs": [{ "name": "partnerA", "type": "address", "indexed": true, "internalType": "address" }, { "name": "partnerB", "type": "address", "indexed": true, "internalType": "address" }, { "name": "rewardEach", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "error", "name": "AddressEmptyCode", "inputs": [{ "name": "target", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC1967InvalidImplementation", "inputs": [{ "name": "implementation", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC1967NonPayable", "inputs": [] },
  { "type": "error", "name": "FailedCall", "inputs": [] },
  { "type": "error", "name": "HumanBond__CannotProposeToSelf", "inputs": [] },
  { "type": "error", "name": "HumanBond__CooldownActive", "inputs": [] },
  { "type": "error", "name": "HumanBond__DissolutionAlreadyRequested", "inputs": [] },
  { "type": "error", "name": "HumanBond__DissolutionDelayNotMet", "inputs": [] },
  { "type": "error", "name": "HumanBond__DissolutionDelayElapsed", "inputs": [] },
  { "type": "error", "name": "HumanBond__InvalidAddress", "inputs": [] },
  { "type": "error", "name": "HumanBond__NoActiveBond", "inputs": [] },
  { "type": "error", "name": "HumanBond__NoDissolutionRequest", "inputs": [] },
  { "type": "error", "name": "HumanBond__NotProposedToYou", "inputs": [] },
  { "type": "error", "name": "HumanBond__NotYourBond", "inputs": [] },
  { "type": "error", "name": "HumanBond__NothingToClaim", "inputs": [] },
  { "type": "error", "name": "HumanBond__ProposalAlreadyExists", "inputs": [] },
  { "type": "error", "name": "HumanBond__UserAlreadyBonded", "inputs": [] },
  { "type": "error", "name": "InvalidInitialization", "inputs": [] },
  { "type": "error", "name": "NotInitializing", "inputs": [] },
  { "type": "error", "name": "OwnableInvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "OwnableUnauthorizedAccount", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "UUPSUnauthorizedCallContext", "inputs": [] },
  { "type": "error", "name": "UUPSUnsupportedProxiableUUID", "inputs": [{ "name": "slot", "type": "bytes32", "internalType": "bytes32" }] }
] as const

// TimeToken ABI
export const TIME_TOKEN_ABI = [
  { "type": "constructor", "inputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "allowance", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "spender", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "approve", "inputs": [{ "name": "spender", "type": "address", "internalType": "address" }, { "name": "value", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "authorizedBurn", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "authorizedBurners", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "authorizedMinters", "inputs": [{ "name": "", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "balanceOf", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "burn", "inputs": [{ "name": "value", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "burnFrom", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }, { "name": "value", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "decimals", "inputs": [], "outputs": [{ "name": "", "type": "uint8", "internalType": "uint8" }], "stateMutability": "view" },
  { "type": "function", "name": "mint", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "name", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "renounceOwnership", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setBurner", "inputs": [{ "name": "burner", "type": "address", "internalType": "address" }, { "name": "authorized", "type": "bool", "internalType": "bool" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "setMinter", "inputs": [{ "name": "minter", "type": "address", "internalType": "address" }, { "name": "authorized", "type": "bool", "internalType": "bool" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "symbol", "inputs": [], "outputs": [{ "name": "", "type": "string", "internalType": "string" }], "stateMutability": "view" },
  { "type": "function", "name": "totalSupply", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "transfer", "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, { "name": "value", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "transferFrom", "inputs": [{ "name": "from", "type": "address", "internalType": "address" }, { "name": "to", "type": "address", "internalType": "address" }, { "name": "value", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "transferOwnership", "inputs": [{ "name": "newOwner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "event", "name": "Approval", "inputs": [{ "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "spender", "type": "address", "indexed": true, "internalType": "address" }, { "name": "value", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "BurnerSet", "inputs": [{ "name": "burner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "authorized", "type": "bool", "indexed": false, "internalType": "bool" }], "anonymous": false },
  { "type": "event", "name": "MinterSet", "inputs": [{ "name": "minter", "type": "address", "indexed": true, "internalType": "address" }, { "name": "authorized", "type": "bool", "indexed": false, "internalType": "bool" }], "anonymous": false },
  { "type": "event", "name": "OwnershipTransferred", "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "Transfer", "inputs": [{ "name": "from", "type": "address", "indexed": true, "internalType": "address" }, { "name": "to", "type": "address", "indexed": true, "internalType": "address" }, { "name": "value", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "error", "name": "ERC20InsufficientAllowance", "inputs": [{ "name": "spender", "type": "address", "internalType": "address" }, { "name": "allowance", "type": "uint256", "internalType": "uint256" }, { "name": "needed", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "ERC20InsufficientBalance", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }, { "name": "balance", "type": "uint256", "internalType": "uint256" }, { "name": "needed", "type": "uint256", "internalType": "uint256" }] },
  { "type": "error", "name": "ERC20InvalidApprover", "inputs": [{ "name": "approver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC20InvalidReceiver", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC20InvalidSender", "inputs": [{ "name": "sender", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "ERC20InvalidSpender", "inputs": [{ "name": "spender", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "InvalidAddress", "inputs": [] },
  { "type": "error", "name": "NotAuthorized", "inputs": [] },
  { "type": "error", "name": "OwnableInvalidOwner", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }] },
  { "type": "error", "name": "OwnableUnauthorizedAccount", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }] }
] as const
